# Generated by Django 4.2.5 on 2023-11-12 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Item', '0003_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='category',
            new_name='course_categories',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='name',
            new_name='course_name',
        ),
    ]
